# Uncomment the next line to define a global platform for your project

platform :ios, '8.0'

target 'RuitaiyuanSafeProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RuitaiyuanSafeProject

pod 'AFNetworking'
pod 'SDWebImage', '~> 4.0'
pod 'MJRefresh'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'SVProgressHUD'
pod 'JPush'
#真机+模拟器
pod "PLRTCStreamingKit", :podspec => 'https://raw.githubusercontent.com/pili-engineering/PLRTCStreamingKit/master/PLRTCStreamingKit-Universal.podspec'

end
