# Uncomment the next line to define a global platform for your project

platform :ios, '8.0'

target 'RuitaiyuanSafeProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RuitaiyuanSafeProject

pod 'AFNetworking'
pod 'PLRTCStreamingKit'
pod 'SDWebImage', '~> 4.0'
pod 'MJRefresh'
pod 'PLRTCStreamingKit'




end
